^Fire:
	Inherits: ^FireWH
	ReloadDelay: 20
	Range: 0c0
	Projectile: InstantExplode
	Warhead@1Dam: SpreadDamage
		Falloff: 100, 50
		Spread: 1c0
		Versus:
			Building: 25

Fire1:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 16

Fire2:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 12

Fire3:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 8

Fire4:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 4

BFire1:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 24

BFire2:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 20

BFire3:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 16

BFire4:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 12

Tiberium:
	Inherits: ^TiberiumWH
	ReloadDelay: 8
	Range: 0c0
	Projectile: InstantExplode
	Warhead@1Dam: SpreadDamage
		Falloff: 100, 80
		Spread: 1c0
		Damage: 4
		DamageTypes: TriggerVisceroid

^Repair:
	ReloadDelay: 0
	Range: 0c0
	Projectile: InstantExplode
	Warhead@Damage: SpreadDamage
		Falloff: 100, 0
		Spread: 7c73
		DamageTypes: Repair
		ValidStances: Ally
	Warhead@Condition: GrantExternalCondition
		Condition: FeatureBuffRepair
		Range: 7c73
		Duration: 1
		ValidStances: Ally

^GlobalRepair:
	ReloadDelay: 0
	Warhead@Global: GlobalExplodeWeapon
		ValidStances: Ally
		Weapon: ^GlobalRepair1

^GlobalRepair1:
	Warhead@Damage: TargetDamage
		ValidStances: Ally
	Warhead@Condition: GrantExternalCondition
		Condition: FeatureBuffRepair
		Range: 0c0
		Duration: 1
		ValidStances: Ally

RepairInfantry:
	ReloadDelay: 10
	Inherits: ^Repair
	Warhead@Damage:
		ValidTargets: Infantry
		Spread: 4c248
		Damage: -5
	Warhead@Condition:
		ValidTargets: Infantry
		Range: 4c248
		Duration: 10

RepairCyborg:
	Inherits: ^Repair
	Warhead@Damage:
		ValidTargets: Cyborg
		Damage: -4
	Warhead@Condition:
		ValidTargets: Cyborg

RepairVehicle:
	Inherits: ^Repair
	Warhead@Damage:
		ValidTargets: Vehicle
		Damage: -4
	Warhead@Condition:
		ValidTargets: Vehicle

RepairInfantryGlobal:
	ReloadDelay: 10
	Inherits: ^GlobalRepair
	Warhead@Global:
		Weapon: RepairInfantryGlobal1

RepairInfantryGlobal1:
	Inherits: ^GlobalRepair1
	Warhead@Damage:
		ValidTargets: Infantry
		Damage: -5
	Warhead@Condition:
		ValidTargets: Infantry
		Duration: 10

