^Fire:
	Inherits: ^FireWH
	ReloadDelay: 20
	Range: 0c0
	Projectile: InstantExplode
	Warhead@1Dam: SpreadDamage
		Falloff: 100, 50
		Spread: 1c0
		Versus:
			Building: 25

Fire1:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 16

Fire2:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 12

Fire3:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 8

Fire4:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 4

BFire1:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 24

BFire2:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 20

BFire3:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 16

BFire4:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 12

Tiberium:
	Inherits: ^TiberiumWH
	ReloadDelay: 8
	Range: 0c0
	Projectile: InstantExplode
	Warhead@1Dam: SpreadDamage
		Falloff: 100, 80
		Spread: 1c0
		Damage: 4
		DamageTypes: TriggerVisceroid

^Repair:
	ReloadDelay: 1
	Range: 0c0
	Projectile: InstantExplode
	Warhead@Damage: SpreadDamage
		Falloff: 100, 0
		Spread: 7c73
		DamageTypes: Repair
	Warhead@Condition: GrantExternalCondition
		Condition: FeatureBuffRepair
		Spread: 7c73
		Duration: 1

^GlobalRepair:
	Warhead@Damage: SpreadDamage
		Falloff: 100, 0
		Spread: 1000000c0
	Warhead@Condition: GrantExternalCondition
		Condition: FeatureBuffRepair
		Spread: 1000000c0

RepairInfantry:
	ReloadDelay: 10
	Inherits: ^Repair
	Warhead@Damage: SpreadDamage
		ValidTargets: Infantry
		Spread: 4c248
		Damage: -5
	Warhead@Condition: GrantExternalCondition
		ValidTargets: Infantry
		Spread: 4c248
		Duration: 10

RepairCyborg:
	Inherits: ^Repair
	Warhead@Damage: SpreadDamage
		ValidTargets: Cyborg
		Damage: -4
	Warhead@Condition: GrantExternalCondition
		ValidTargets: Cyborg

RepairVehicle:
	Inherits: ^Repair
	Warhead@Damage: SpreadDamage
		ValidTargets: Vehicle
		Damage: -4
	Warhead@Condition: GrantExternalCondition
		ValidTargets: Vehicle

RepairInfantryGlobal:
	Inherits: RepairInfantry
	Inherits@GlobalRepair: ^GlobalRepair
