^Fire:
	Inherits: ^FireWH
	ReloadDelay: 20
	Range: 0c0
	Projectile: InstantExplode
	Warhead@1Dam: SpreadDamage
		AffectsParent: True
		Falloff: 100, 50
		Spread: 1c0
		Versus:
			Building: 25

Fire1:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 16000

Fire2:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 12000

Fire3:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 8000

Fire4:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 4000

BFire1:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 24000

BFire2:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 20000

BFire3:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 16000

BFire4:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 12000

Tiberium:
	Inherits: ^TiberiumWH
	ReloadDelay: 8
	Range: 0c0
	Projectile: InstantExplode
	Warhead@1Dam: SpreadDamage
		AffectsParent: True
		Falloff: 100, 80
		Spread: 1c0
		Damage: 4000
		DamageTypes: TriggerVisceroid

TiberiumWeak:
	Inherits: Tiberium
	ReloadDelay: 16
