^Fire:
	Inherits: ^FireWH
	ReloadDelay: 20
	Range: 0c0
	Projectile: InstantExplode
	Warhead@1Dam: SpreadDamage
		Falloff: 100, 50
		Spread: 1c0
		Versus:
			Building: 25

Fire1:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 16

Fire2:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 12

Fire3:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 8

Fire4:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 4

BFire1:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 24

BFire2:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 20

BFire3:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 16

BFire4:
	Inherits: ^Fire
	Warhead@1Dam: SpreadDamage
		Damage: 12

Tiberium:
	Inherits: ^TiberiumWH
	ReloadDelay: 8
	Range: 0c0
	Projectile: InstantExplode
	Warhead@1Dam: SpreadDamage
		Falloff: 100, 80
		Spread: 1c0
		Damage: 4
		DamageTypes: TriggerVisceroid
